hpcdata <- read.delim2("household_power_consumption.txt", header = TRUE, sep = ";", na.strings="?")
subhpc <- subset(hpcdata, Date=="1/2/2007" | Date=="2/2/2007")
subhpc$datetime<-strptime(paste(subhpc$Date,subhpc$Time), "%d/%m/%Y %H:%M:%S")
subhpc$Sub_metering_1<-as.numeric(as.character(subhpc$Sub_metering_1))
subhpc$Sub_metering_2<-as.numeric(as.character(subhpc$Sub_metering_2))
subhpc$Sub_metering_3<-as.numeric(as.character(subhpc$Sub_metering_3))

png(file="plot3.png", width=480, height=480)
plot(subhpc$datetime,subhpc$Sub_metering_1,type="n", xlab="", ylab="Energy sub metering")
lines(subhpc$datetime,subhpc$Sub_metering_1)
lines(subhpc$datetime,subhpc$Sub_metering_2,col="red")
lines(subhpc$datetime,subhpc$Sub_metering_3,col="blue")
legend(x="topright",lwd=c(1,1,1), col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
